### ISSUE TITLE
Pyglui Timeline_Menu crash 

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pyglui#67]
Error report from Pupil Player when trying to drag the timeline up after detection calibration markers for offline calibration. 

```python
player - [ERROR] launchables.player: Process Player crashed with trace:
Traceback (most recent call last):
  File "/home/pupil-labs/Documents/pupil_labs/pupil/pupil_src/launchables/player.py", line 457, in player
    unused_elements = g_pool.gui.update()
  File "pyglui/ui.pyx", line 203, in pyglui.ui.UI.update
  File "pyglui/ui.pyx", line 172, in pyglui.ui.UI.draw
  File "pyglui/menus.pxi", line 712, in pyglui.ui.Container.draw
  File "pyglui/menus.pxi", line 732, in pyglui.ui.Container.draw
  File "pyglui/menus.pxi", line 712, in pyglui.ui.Container.draw
  File "pyglui/menus.pxi", line 732, in pyglui.ui.Container.draw
  File "pyglui/menus.pxi", line 760, in pyglui.ui.Timeline_Menu.draw
  File "pyglui/menus.pxi", line 764, in pyglui.ui.Timeline_Menu.draw
  File "pyglui/menus.pxi", line 531, in pyglui.ui.Scrolling_Menu.draw
  File "pyglui/menus.pxi", line 541, in pyglui.ui.Scrolling_Menu.draw
  File "pyglui/menus.pxi", line 568, in pyglui.ui.Scrolling_Menu.draw_scroll_window_elements
  File "pyglui/timelines.pxi", line 20, in pyglui.ui.Timeline.draw
  File "pyglui/timelines.pxi", line 42, in pyglui.ui.Timeline.draw
TypeError: draw_sections() takes 3 positional arguments but 4 were given
```

**Comment by papr** [comment]
This is because you are using pyglui v1.10 but an older version of Pupil. Merging #869 will fix this.

**Comment by willpatera** [comment]
Noted. Let's close this when https://github.com/pupil-labs/pupil/pull/869 is merged.
